terminate called after throwing an instance of 'std::bad_alloc'
  what():  St9bad_alloc
sh: line 1:  1363 Aborted                 ./htn-solver2 --use_qvalues htn_domain_original.pddl htn_probs/024.htn_prob

real	0m54.310s
user	0m48.023s
sys	0m6.284s
