terminate called after throwing an instance of 'std::bad_alloc'
  what():  St9bad_alloc
sh: line 1:  1208 Aborted                 ./htn-solver2 htn_domain_novalues.pddl htn_probs/023.htn_prob

real	0m49.137s
user	0m42.721s
sys	0m6.214s
